### ISSUE TITLE
Kanban board set up

### ISSUE THREAD

**Issue by NataliaPoletaeva** [NataliaPoletaeva/catalog-of-my-things#26]
In this PR, we have:
- set up the [Kanban board](https://github.com/NataliaPoletaeva/catalog-of-my-things/projects/1) for the project;
- divided the workload between three people;
- assigned the tasks according to next list:
  - Team Member №1- @gtekle;
  - Team Member №2 - @mrparkersson; 
  - Team Member №3 - @NataliaPoletaeva.

**Comment by julie-ify** [comment]
Hi @NataliaPoletaeva, @gtekle, @mrparkersson, 

## APPROVED ✔️ ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
